### ISSUE TITLE
Странности с ссылками на профили

### ISSUE THREAD

**Issue by maksalees** [alexflitcher1/twitter23#15]
Почему при переходе на свой профиль, ссылка - http://twitter23.witch.quest/me, а не просто ссылка на профиль?
Почему ссылки на чужие профили имеют вид http://twitter23.witch.quest/profile?id=user а не например как в оригинальном Twitter http://twitter23.witch.quest/user?

**Comment by Defenders08** [comment]
++++ Нада сделать просто так
/defenders08

**Comment by maksalees** [comment]
> ++++ Нада сделать просто так /defenders08

Я про это и написал. Используй реакции вместо написания лишних комментариев

**Comment by Defenders08** [comment]
@maksalees ок
