### ISSUE TITLE
Кастомизация

### ISSUE THREAD

**Issue by Defenders08** [alexflitcher1/twitter23#58]
Сделать нормальную кастомизацию, а именно:
1. Цветовые схемы и тёмную тему. Нужно чтобы при выборе тёмной темы цветовая схема сохранялась
2. Кастомизация профила (кастомный CSS). Нужно сделать в настройках профиля возможность добавление кастомного CSS для своей страницы чтобы при заходе другого юзера внешний вид менялся (прим. MYSPACE93)

**Comment by Defenders08** [comment]
Добавить в настройках пункт (в основных) как "Собственное оформление" с кастомным CSS. То есть:
Будет можно сделать два кастомных цсс:
1. В настройках профиля CSS для своего профиля (который люди будут видеть при заходе на ваш аккаунт)
2. В основных настройках для всего сайта

**Comment by alexflitcher1** [comment]
https://github.com/twitter23/twitter23/commit/7858b8f1d0eb34b4afc2893c59986f53fce39b1a
